- backend/src/main/java/linklibrary/controller/TestController.java
- backend/src/main/java/linklibrary/cors/WebConfig.java
- backend/src/main/java/linklibrary/swagger/SwaggerConfig.java
cors에러, 
testController 작성,
swagger bean에 등록
> feat: 백엔드 개발 환경 세팅

- backend/src/main/java/linklibrary/controller/TestController.java
> feat: 리액트 연동용 테스트 코드 추가

- backend/src/main/java/linklibrary/entity/User.java
- backend/src/main/java/linklibrary/repository/UserRepository.java
> refactor: User 클래스 명 변경

- backend/src/main/java/linklibrary/entity/User.java
> refactor : 충돌시험.게터세터

- backend/src/main/java/linklibrary/entity/User.java
- backend/src/main/java/linklibrary/repository/UserRepository.java
> Plan11plan

- backend/src/main/java/linklibrary/entity/User.java
- backend/src/main/java/linklibrary/repository/UserRepository.java
> refactor: User 엔티티 수정

- backend/src/main/java/linklibrary/entity/Category.java
- backend/src/main/java/linklibrary/entity/Post.java
- backend/src/main/java/linklibrary/entity/Role.java
- backend/src/main/java/linklibrary/entity/User.java
- backend/src/main/java/linklibrary/repository/CategoryRepository.java
- backend/src/main/java/linklibrary/repository/PostRepository.java
> feat: entity 개발

- backend/src/main/java/linklibrary/security/CustomAuthFailureHandler.java
- backend/src/main/java/linklibrary/security/CustomLoginSuccessHandler.java
- backend/src/main/java/linklibrary/security/SecurityConfig.java
- backend/src/main/java/linklibrary/security/UserDetailsServiceImpl.java
> feat: 스프링 시큐리티 설정

- backend/src/main/java/linklibrary/controller/PostController.java
- backend/src/main/java/linklibrary/service/PostService.java
> feat: 포스트 삭제 기능 추가

- backend/build.gradle
- backend/src/main/java/linklibrary/controller/ExceptionController.java
- backend/src/main/java/linklibrary/controller/PostController.java
- backend/src/main/java/linklibrary/dto/PostFormDto.java
- backend/src/main/java/linklibrary/dto/ResponseData.java
- backend/src/main/java/linklibrary/entity/Category.java
- backend/src/main/java/linklibrary/entity/Post.java
- backend/src/main/java/linklibrary/entity/User.java
- backend/src/main/java/linklibrary/mapper/PostMapper.java
- backend/src/main/java/linklibrary/security/SecurityConfig.java
- backend/src/main/java/linklibrary/service/PostService.java
- backend/src/main/java/linklibrary/swagger/SwaggerConfig.java
전역 예외 클래스 생성,
반환 전용 클래스 생성,
validation 적용
> refactor: 코드 일부 수정

- backend/src/main/java/linklibrary/controller/TestController.java
- backend/src/main/java/linklibrary/dto/CategoryDto.java
- backend/src/main/java/linklibrary/entity/Category.java
- backend/src/main/java/linklibrary/entity/Post.java
- backend/src/main/java/linklibrary/entity/User.java
- backend/src/main/java/linklibrary/repository/CategoryRepository.java
- backend/src/main/java/linklibrary/service/CategoryService.java
Category 에 부모 Category 자식 CategoryLIst를 추가해 계층별 카테고리 기능 구현
> feat: 계층별 카테고리 개발

- backend/build.gradle
- backend/src/main/java/linklibrary/controller/CategoryController.java
- backend/src/main/java/linklibrary/controller/UserController.java
- backend/src/main/java/linklibrary/dto/CategoryDto.java
- backend/src/main/java/linklibrary/dto/JoinFormDto.java
- backend/src/main/java/linklibrary/dto/LoginFormDto.java
- backend/src/main/java/linklibrary/entity/Category.java
- backend/src/main/java/linklibrary/entity/User.java
- backend/src/main/java/linklibrary/repository/CategoryRepository.java
- backend/src/main/java/linklibrary/service/CategoryService.java
- backend/src/main/java/linklibrary/service/PostService.java
- backend/src/test/java/linklibrary/service/CategoryServiceTest.java
- backend/src/test/java/linklibrary/service/UserServiceTest.java
> 카테고리 CRUD, 테스트코드 작성

- backend/src/main/java/linklibrary/controller/UserController.java
- backend/src/main/java/linklibrary/service/UserService.java
- backend/src/test/java/linklibrary/service/UserServiceTest.java
feat: 아이디 중복 체크 개발
테스트 코드 작성 완료
> feat: 아이디 중복 체크 개발

- backend/src/main/java/linklibrary/InitDB.java
- backend/src/main/java/linklibrary/LinkLibraryApplication.java
- backend/src/main/java/linklibrary/entity/BaseEntity.java
- backend/src/main/java/linklibrary/entity/Post.java
- backend/src/main/java/linklibrary/entity/User.java
- backend/src/main/java/linklibrary/service/CategoryService.java
- backend/src/main/java/linklibrary/service/PostService.java
- backend/src/main/java/linklibrary/service/UserService.java
> feat: auditing, dbInit 개발

- backend/src/main/java/linklibrary/InitDB.java
- backend/src/main/java/linklibrary/controller/UserController.java
- backend/src/main/java/linklibrary/dto/ProfileImgDto.java
- backend/src/main/java/linklibrary/dto/ValidateIdForm.java
- backend/src/main/java/linklibrary/dto/ValidateNicknameForm.java
- backend/src/main/java/linklibrary/entity/ProfileImg.java
- backend/src/main/java/linklibrary/entity/User.java
- backend/src/main/java/linklibrary/exception/ExceptionController.java
- backend/src/main/java/linklibrary/repository/ProfileImgRepository.java
- backend/src/main/java/linklibrary/repository/UserRepository.java
- backend/src/main/java/linklibrary/service/CategoryService.java
- backend/src/main/java/linklibrary/service/PostService.java
- backend/src/main/java/linklibrary/service/ProfileImgService.java
- backend/src/main/java/linklibrary/service/UserService.java
- backend/src/main/resources/application.yml
> feat: 이미지 업로드 개발

- backend/src/main/java/linklibrary/controller/UserController.java
- backend/src/main/java/linklibrary/service/ProfileImgService.java
- backend/src/main/resources/application.yml
> refactor: 주석 추가

- backend/src/main/java/linklibrary/controller/PostController.java
- backend/src/main/java/linklibrary/controller/UserController.java
- backend/src/main/java/linklibrary/dto/ValidateIdForm.java
- backend/src/main/java/linklibrary/dto/ValidateNicknameForm.java
- backend/src/main/java/linklibrary/mapper/PostMapper.java
- backend/src/main/java/linklibrary/repository/PostRepository.java
- backend/src/main/java/linklibrary/security/SecurityConfig.java
- backend/src/main/java/linklibrary/security/jwt/JwtAuthenticationFilter.java
- backend/src/main/java/linklibrary/security/jwt/JwtProperties.java
- backend/src/main/java/linklibrary/service/PostService.java
- backend/src/main/java/linklibrary/service/UserService.java
> feat: 진수1 진행상태

- backend/src/main/java/linklibrary/controller/UserController.java
- backend/src/main/java/linklibrary/exception/ExceptionController.java
- backend/src/main/java/linklibrary/security/jwt/JwtProperties.java
- backend/src/main/java/linklibrary/service/ProfileImgService.java
feat: 기존 프로필 사진이 있을 때 사진 업로드 처리
> feat: 기존 프로필 사진이 있을 때 사진 업로드 처리

- backend/build.gradle
- backend/src/main/java/linklibrary/security/SecurityConfig.java
- backend/src/main/java/linklibrary/security/jwt/ExceptionHandlerFilter.java
- backend/src/main/java/linklibrary/security/jwt/JwtAuthenticationFilter.java
- backend/src/main/java/linklibrary/security/jwt/JwtAuthorizationFilter.java
- backend/src/main/java/linklibrary/security/jwt/JwtProperties.java
refactor: 시큐리티에서 나는 예외 처리 잡기(수정 중)
> refactor: 시큐리티에서 나는 예외 처리 잡기(수정 중)

- backend/src/main/java/linklibrary/dto/ValidateIdForm.java
- backend/src/main/java/linklibrary/dto/ValidateNicknameForm.java
fix: 데이터 바인딩 에러 해결
기본 생성자 추가했습니다.
> fix: 데이터 바인딩 에러 해결

- backend/src/main/java/linklibrary/controller/PostController.java
- backend/src/main/java/linklibrary/repository/CategoryRepository.java
- backend/src/main/java/linklibrary/repository/PostRepository.java
- backend/src/main/java/linklibrary/service/PostService.java
> fact: 카테고리 이름으로 전체 조회

- backend/src/main/java/linklibrary/controller/PostController.java
- backend/src/main/java/linklibrary/controller/UserController.java
- backend/src/main/java/linklibrary/dto/ProfileImgDto.java
- backend/src/main/java/linklibrary/dto/UserPageDto.java
- backend/src/main/java/linklibrary/repository/PostRepository.java
- backend/src/main/java/linklibrary/service/PostService.java
> feat: 회원 페이지 조회 개발

- backend/src/main/java/linklibrary/controller/PostController.java
- backend/src/main/java/linklibrary/service/PostService.java
refactor: 카레고리로 전체조회 수정.
(전반적으로 코드를 짰긴했지만
포스트 생성할때 그리고 포스트 찜목록 조회할때
포스트에 카테고리설정하는거는 아직 못했음)
> refactor: 카레고리로 전체조회 수정

- backend/build.gradle
- backend/src/main/java/linklibrary/controller/UserController.java
- backend/src/main/java/linklibrary/dto/CategoryDto.java
- backend/src/main/java/linklibrary/dto/PostFormDto.java
- backend/src/main/java/linklibrary/dto/UserPageDto.java
- backend/src/main/java/linklibrary/mapper/PostMapper.java
- backend/src/main/java/linklibrary/service/PostService.java
- backend/src/test/java/linklibrary/service/CategoryServiceTest.java
- backend/src/test/java/linklibrary/service/PostServiceTest.java
feat: postService 테스트 코드 작성 완료
> feat: postService 테스트 코드 작성 완료

- backend/src/main/java/linklibrary/controller/PostController.java
- backend/src/main/java/linklibrary/dto/PostDto.java
- backend/src/main/java/linklibrary/dto/PostDto1.java
- backend/src/main/java/linklibrary/dto/PostFormDto.java
- backend/src/main/java/linklibrary/mapper/PostMapper.java
- backend/src/main/java/linklibrary/repository/PostRepository.java
- backend/src/main/java/linklibrary/service/PostService.java
refactor: 진수1 포스트조회에 카테고리,페이징추가
> refactor: 진수1 포스트조회에 카테고리,페이징추가

- backend/src/main/java/linklibrary/securityTest/JwtFilter.java
- backend/src/main/java/linklibrary/securityTest/JwtSecurityConfig.java
- backend/src/main/java/linklibrary/securityTest/SecurityConfig.java
- backend/src/main/java/linklibrary/securityTest/TokenProvider.java
- backend/src/main/java/linklibrary/securityTest/redis/RedisRepositoryConfig.java
- backend/src/main/java/linklibrary/securityTest/service/AuthService.java
> feat: 로그아웃 개발 중(미완성)

- backend/src/main/java/linklibrary/controller/UserController.java
- backend/src/main/java/linklibrary/exception/ExceptionController.java
- backend/src/main/java/linklibrary/securityTest/TokenProvider.java
- backend/src/main/java/linklibrary/securityTest/auth/PrincipalDetailService.java
- backend/src/main/java/linklibrary/securityTest/dto/TokenDto.java
- backend/src/main/java/linklibrary/securityTest/service/AuthService.java
- backend/src/main/resources/application.yml
> feat: 아이디, 비밀번호 불일치 시 예외 처리

- backend/src/main/java/linklibrary/swagger/SwaggerConfig.java
> refactor: swagger 접속 주소

- backend/src/main/java/linklibrary/controller/CategoryController.java
- backend/src/main/java/linklibrary/controller/PostController.java
- backend/src/main/java/linklibrary/controller/UserController.java
- backend/src/main/java/linklibrary/dto/LoginFormDto.java
- backend/src/main/java/linklibrary/dto/PostFormDto.java
- backend/src/main/java/linklibrary/dto/ValidateNicknameForm.java
- backend/src/main/java/linklibrary/exception/ExceptionController.java
- backend/src/main/java/linklibrary/service/PostService.java
> feat: swagger 어노테이션 추가

- backend/src/main/java/linklibrary/dto/request/CategoryFormDto.java
- backend/src/main/java/linklibrary/dto/request/JoinFormDto.java
- backend/src/main/java/linklibrary/dto/request/LogoutDto.java
- backend/src/main/java/linklibrary/dto/request/PostFormDto.java
- backend/src/main/java/linklibrary/dto/request/ProfileImgDto.java
- backend/src/main/java/linklibrary/dto/request/ValidateIdForm.java
- backend/src/main/java/linklibrary/dto/request/ValidateNicknameForm.java
- backend/src/main/java/linklibrary/dto/response/CategoryDto.java
- backend/src/main/java/linklibrary/dto/response/MainPageDto.java
- backend/src/main/java/linklibrary/dto/response/PostDto.java
- backend/src/main/java/linklibrary/dto/response/PostDto1.java
- backend/src/main/java/linklibrary/dto/response/UserDto.java
- backend/src/main/java/linklibrary/dto/response/UserPageDto.java
refactor: DTO->스웨거 스키마 애노테이션 추가
> refactor: DTO->스웨거 스키마 애노테이션 추가

- backend/build.gradle
- backend/src/main/java/linklibrary/controller/Test/UserControllerTest.java
- backend/src/main/java/linklibrary/dto/request/test/JoinFormDtoTest.java
- backend/src/main/java/linklibrary/dto/response/PostDto.java
- backend/src/main/java/linklibrary/dto/response/test/CommonResponseDto.java
- backend/src/main/java/linklibrary/mapper/Post/ChangePostMapper.java
- backend/src/main/java/linklibrary/mapper/Post/CreatePostMapper.java
- backend/src/main/java/linklibrary/mapper/Post/MainPageMapper.java
- backend/src/main/java/linklibrary/mapper/PostMapper.java
- backend/src/main/java/linklibrary/mapper/User/JoinMapper.java
- backend/src/main/java/linklibrary/mapper/User/UserPageMapper.java
- backend/src/main/java/linklibrary/security/service/AuthService.java
- backend/src/main/java/linklibrary/security/service/test/AuthServiceTest.java
- backend/src/main/java/linklibrary/security/service/test/AuthenticationInvalidException.java
- backend/src/main/java/linklibrary/service/PostService.java
- backend/src/main/java/linklibrary/service/UserService.java
feat: 회원가입 요청받고 응답까지 다른 방식이 있어서 한번 진수님은 이거에 대해 어떻게 생각하는지 알고 싶어요 한
> feat: 회원가입 요청받고 응답까지 다른 방식이 있어서 한번 진수님은 이거에 대해 어떻게 생각하는지 알고 싶어요 한

- backend/src/main/java/linklibrary/controller/PostController.java
- backend/src/main/java/linklibrary/mapper/PostMapper.java
- backend/src/main/java/linklibrary/security/auth/PrincipalDetailService.java
- backend/src/main/java/linklibrary/security/service/test/AuthServiceTest.java
주석 질문에 대한 저의 대답
시큐리티-오스-프린시펄 디테일 서비스
> 주석 질문에 대한 저의 대답

- backend/src/main/java/linklibrary/controller/CategoryController.java
- backend/src/main/java/linklibrary/controller/PostController.java
- backend/src/main/java/linklibrary/controller/UserController.java
- backend/src/main/java/linklibrary/dto/response/PostDto1.java
- backend/src/main/java/linklibrary/entity/Category.java
- backend/src/main/java/linklibrary/entity/Post.java
- backend/src/main/java/linklibrary/entity/ProfileImg.java
- backend/src/main/java/linklibrary/entity/User.java
- backend/src/main/java/linklibrary/repository/CategoryRepository.java
- backend/src/main/java/linklibrary/repository/PostRepository.java
- backend/src/main/java/linklibrary/repository/PostRepositoryImpl.java
- backend/src/main/java/linklibrary/repository/ProfileImgRepository.java
- backend/src/main/java/linklibrary/service/CategoryService.java
- backend/src/main/java/linklibrary/service/PostService.java
- backend/src/main/java/linklibrary/service/ProfileImgService.java
- backend/src/main/java/linklibrary/service/UserService.java
- backend/src/main/resources/application.yml
- backend/src/test/java/linklibrary/service/CategoryServiceTest.java
> fix: 버그들 수정

- backend/src/main/java/linklibrary/service/CategoryService.java
2023-05-18 삭제카테고리  서비스 로직 일부 추가
> 2023-05-18 삭제카테고리 로직 일부 추가

- backend/src/main/java/linklibrary/dto/response/MainPageDto.java
- backend/src/main/java/linklibrary/service/PostService.java
> 방금 수정 지운 코드

- backend/src/main/java/linklibrary/dto/response/MainPageDto.java
- backend/src/main/java/linklibrary/service/PostService.java
> 해당 카테고리 포스트 사이즈 추가

- backend/src/main/java/linklibrary/service/PostService.java
> update PostService 2트

- backend/src/main/java/linklibrary/service/UserService.java
> refact: 비밀번호 없을때 추가 V2

- backend/src/main/java/linklibrary/dto/request/UpdateUserPageFormDto.java
> refact: 마이페이지 수정 코드 V2

- backend/src/main/java/linklibrary/service/UserService.java
> refact: 마이페이지 수정 V3

- backend/src/main/java/linklibrary/service/UserService.java
> refact : 마이페이지 수정 V4

- backend/src/main/java/linklibrary/dto/request/UpdateUserPageFormDto.java
- backend/src/main/java/linklibrary/service/UserService.java
> refact: 마이페이지 수정 V5

- backend/src/main/java/linklibrary/dto/request/UpdateUserPageFormDto.java
> refact: 마이페이지 수정 V6

- backend/src/main/java/linklibrary/service/UserService.java
> refact : 마이페이지 수정 V7
